export const RENDER_CONSTANTS = {
    CAPTURE_SCALE_FACTOR: 4,
    STATS_UPDATE_INTERVAL_MS: 500,
    DEFAULT_VIDEO_WIDTH: 1920,
    DEFAULT_VIDEO_HEIGHT: 1080,
    CLIPBOARD_WIDTH: 150,
    VIDEO_RECORDING_FPS: 30,
    VIDEO_BITRATE: 2500000,
    FLASH_DURATION_MS: 200,
    CLIPBOARD_SUCCESS_DURATION_MS: 2000,
    CAMERA_FLIP_DURATION_MS: 600,
    COPY_SUCCESS_DURATION_MS: 1000,
} as const

export const SETTINGS_CONSTANTS = {
    DEFAULT_RESOLUTION: 0.2,
    DEFAULT_FONT_SIZE: 10,
    DEFAULT_CONTRAST: 1.2,
    DEFAULT_BRIGHTNESS: 0,
    DEFAULT_COLOR_MODE: false,
    DEFAULT_INVERT: false,
    DEFAULT_CHARACTER_SET: 'standard' as const,
} as const

export const SLIDER_CONSTANTS = {
    FONT_SIZE: { min: 6, max: 30, step: 1 },
    CONTRAST: { min: 0.5, max: 3.0, step: 0.1 },
    BRIGHTNESS: { min: -100, max: 100, step: 1 },
} as const
